
# Most popular from https://docs.publishing.service.gov.uk/document-types/contact.html (20 February 2017)
contact_1: /government/organisations/hm-revenue-customs/contact/income-tax-enquiries-for-individuals-pensioners-and-employees
contact_2: /government/organisations/hm-revenue-customs/contact/self-assessment
contact_3: /government/organisations/hm-revenue-customs/contact/employer-enquiries
contact_4: /government/organisations/hm-revenue-customs/contact/probate-and-inheritance-tax-enquiries
contact_5: /government/organisations/hm-revenue-customs/contact/income-tax-and-capital-gains-tax-enquiries-for-non-uk-residents
contact_6: /government/organisations/hm-revenue-customs/contact/stamp-duty-enquiries-shares-and-land
contact_7: /government/organisations/hm-revenue-customs/contact/self-assessment-forms-ordering
contact_8: /government/organisations/hm-revenue-customs/contact/trusts
contact_9: /government/organisations/hm-revenue-customs/contact/gambling-duties
contact_10: /government/organisations/hm-revenue-customs/contact/welsh-language-helpline-for-debt-management

# Most popular HTML publications
html_publication_1: /government/publications/car-show-me-tell-me-vehicle-safety-questions/car-show-me-tell-me-vehicle-safety-questions
html_publication_2: /government/publications/tax-and-tax-credit-rates-and-thresholds-for-2017-18/tax-and-tax-credit-rates-and-thresholds-for-2017-18
html_publication_3: /government/publications/rates-and-allowances-national-insurance-contributions/rates-and-allowances-national-insurance-contributions
html_publication_4: /government/publications/rates-and-allowances-income-tax/income-tax-rates-and-allowances-current-and-past
html_publication_5: /government/publications/income-tax-personal-allowance-and-basic-rate-limit-for-2017-to-2018/income-tax-personal-allowance-and-basic-rate-limit-for-2017-to-2018
html_publication_6: /government/publications/recognising-the-terrorist-threat/recognising-the-terrorist-threat
html_publication_7: /government/publications/tax-and-tax-credit-rates-and-thresholds-for-2016-17/tax-and-tax-credit-rates-and-thresholds-for-2016-17
html_publication_8: /government/publications/advisory-fuel-rates/advisory-fuel-rates-from-1-march-2016
html_publication_9: /government/publications/apprenticeship-levy-how-it-will-work/apprenticeship-levy-how-it-will-work
html_publication_10: /government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets

# Right to left HTML publications
rtl_publication_1: /government/publications/saudi-arabia-country-of-concern--2/968738
rtl_publication_2: /government/publications/apply-for-a-uk-visa-in-saudi-arabia/%D8%B7%D9%84%D8%A8-%D8%AA%D8%A3%D8%B4%D9%8A%D8%B1%D8%A9-%D9%84%D9%84%D9%85%D9%84%D9%83%D8%A9-%D8%A7%D9%84%D9%85%D8%AA%D8%AD%D8%AF%D8%A9-%D9%85%D9%86-%D8%A7%D9%84%D9%85%D9%85%D9%84%D9%83%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9-%D8%B9%D9%85%D9%84%D9%8A%D8%A9-%D8%A7%D9%84%D8%B7%D9%84%D8%A8
rtl_publication_3: /government/publications/apply-for-a-uk-visa-in-kuwait/%D8%B7%D9%84%D8%A8-%D8%AA%D8%A3%D8%B4%D9%8A%D8%B1%D8%A9-%D9%84%D8%AF%D9%88%D9%84%D8%A9-%D9%85%D9%86-%D8%AF%D9%88%D9%84-%D8%A7%D9%84%D9%83%D9%88%D9%85%D9%88%D9%86%D9%88%D9%84%D8%AB-%D8%A3%D9%88-%D8%A3%D9%82%D8%A7%D9%84%D9%8A%D9%85-%D9%85%D8%A7-%D9%88%D8%B1%D8%A7%D8%A1-%D8%A7%D9%84%D8%A8%D8%AD%D8%A7%D8%B1-%D8%A7%D9%84%D8%A8%D8%B1%D9%8A%D8%B7%D8%A7%D9%86%D9%8A%D8%A9-%D9%85%D9%86-%D8%A7%D8%B3%D9%85-%D8%A7%D9%84%D8%AF%D9%88%D9%84%D8%A9

# Most popular guides (8 May 2017)
guide_0: '/log-in-register-hmrc-online-services'
guide_1: '/log-in-file-self-assessment-tax-return'
guide_2: '/log-in-register-hmrc-online-services/sign-in'
guide_3: '/change-address-driving-licence'
guide_4: '/standard-visitor-visa'
guide_5: '/renew-adult-passport/renew'
guide_6: '/self-assessment-tax-returns'
guide_7: '/claim-tax-refund/too-much-tax-taken-from-your-pay'
guide_8: '/vehicle-tax-rate-tables'
guide_9: '/claim-tax-refund/overview'

# Most popular specialist docs (25 April 2017)
specialist_document_1: /business-finance-support/start-up-loans-uk
specialist_document_2: /drug-device-alerts/class-2-medicines-recall-diclo-sr-75-tablets-diclofenac-sodium
specialist_document_3: /drug-device-alerts/field-safety-notice-27-march-to-31-march-2017
specialist_document_4: /drug-device-alerts/field-safety-notice-03-april-to-07-april-2017
specialist_document_5: /drug-device-alerts/field-safety-notices-20-march-24-march-2017
specialist_document_6: /maib-reports/accidents-on-board-yacht-cv21-resulting-in-loss-of-2-lives
specialist_document_7: /drug-safety-update/sglt2-inhibitors-updated-advice-on-increased-risk-of-lower-limb-amputation-mainly-toes
specialist_document_8: /drug-device-alerts/field-safety-notice-10-april-to-14-april-2017
specialist_document_9: /cma-cases/digital-comparison-tools-market-study
specialist_document_10: /cma-cases/review-of-banking-for-small-and-medium-sized-businesses-smes-in-the-uk

# Top 2 specialist docs for each specialist document type, excluding those above (25 April 2017)
specialist_document_11: /drug-safety-update/paracetamol-updated-dosing-for-children-to-be-introduced
specialist_document_12: /drug-safety-update/hyoscine-butylbromide-buscopan-injection-risk-of-serious-adverse-effects-in-patients-with-underlying-cardiac-disease
specialist_document_13: /international-development-funding/uk-aid-match
specialist_document_14: /international-development-funding/uk-aid-direct
specialist_document_15: /aaib-reports/aircraft-accident-report-aar-1-2017-g-bxfi-22-august-2015
specialist_document_16: /aaib-reports/aaib-investigation-to-piper-l18c-super-cub-g-axlz
specialist_document_17: /raib-reports/fatal-accident-near-david-lane-tram-stop
specialist_document_18: /raib-reports/track-workers-class-investigation
specialist_document_19: /maib-reports/contact-made-by-passenger-ferry-uriah-heep-with-hythe-pier
specialist_document_20: /maib-reports/collision-between-ro-ro-freight-ferry-petunia-seaways-and-historic-motor-launch-peggotty
specialist_document_21: /countryside-stewardship-grants/permanent-grassland-with-very-low-inputs-outside-sdas-gs2
specialist_document_22: /countryside-stewardship-grants/management-of-hedgerows-be3
specialist_document_23: /business-finance-support/childcare-business-grants-england
specialist_document_24: /business-finance-support/business-solutions-south-west-england
specialist_document_25: /dfid-research-outputs/fair-society-healthy-lives-the-marmot-review-strategic-review-of-health-inequalities-in-england-post-2010
specialist_document_26: /dfid-research-outputs/girl-landscaping-studies-pakistan-nepal-and-bangladesh
specialist_document_27: /tax-and-chancery-tribunal-decisions/seven-individuals-v-the-commissioners-for-hm-revenue-and-customs-2017-ukut-0132-tcc
specialist_document_28: /tax-and-chancery-tribunal-decisions/tayo-bailey-others-and-trusteees-of-manchester-new-moston-v-the-charity-commission-for-england-and-wales-2017-ukut-0134-tcc
specialist_document_29: /employment-tribunal-decisions/mr-d-kinnear-v-marley-eternit-ltd-t-a-marley-contract-services-4105271-2016
specialist_document_30: /employment-tribunal-decisions/mr-d-templeton-and-others-v-the-rangers-football-club-ltd-4105211-2016
specialist_document_31: /employment-appeal-tribunal-decisions/london-borough-of-haringey-v-mrs-c-a-o-brien-ukeat-0004-16-la
specialist_document_32: /employment-appeal-tribunal-decisions/kingsmoor-packaging-ltd-v-mr-t-fytch-ukeat-0011-16-joj
specialist_document_33: /administrative-appeals-tribunal-decisions/rj-gmcl-and-cs-v-secretary-of-state-for-work-and-pensions-v-rj-pip-2017-ukut-105-aac
specialist_document_34: /administrative-appeals-tribunal-decisions/mr-v-secretary-of-state-for-work-and-pensions-pip-2017-ukut-46-aac
specialist_document_35: /service-standard-reports/apply-for-a-budgeting-loan-alpha-assessment
specialist_document_36: /service-standard-reports/apply-for-a-budgeting-loan
specialist_document_37: /european-structural-investment-funds/business-development
specialist_document_38: /european-structural-investment-funds/learning-and-skills-project-call-in-sheffield-city-region-lep-oc28s17p0733
specialist_document_39: /asylum-support-tribunal-decisions/cs-v-secretary-of-state-for-the-home-department-as-12-12-29244
specialist_document_40: /asylum-support-tribunal-decisions/am-v-secretary-of-state-for-the-home-department-as-14-11-32141

topical_event_about_page_slim: '/government/topical-events/battle-of-the-somme-centenary-commemorations/about'
topical_event_about_page: '/government/topical-events/ebola-virus-government-response/about'

# Most visited topical_event_about_page pages (2 September 2016)
topical_event_about_page_1: '/government/topical-events/eu-referendum/about'
topical_event_about_page_2: '/government/topical-events/daesh/about'
topical_event_about_page_3: '/government/topical-events/anti-corruption-summit-london-2016/about'
topical_event_about_page_4: '/government/topical-events/national-apprenticeship-week-2016/about'
topical_event_about_page_5: '/government/topical-events/scottish-independence-referendum/about'
topical_event_about_page_6: '/government/topical-events/national-apprenticeship-awards/about'
topical_event_about_page_7: '/government/topical-events/supporting-syria-conference-2016/about'
topical_event_about_page_8: '/government/topical-events/farming/about'
topical_event_about_page_9: '/government/topical-events/girl-summit-2014/about'

working_group_long: '/government/groups/benefits-credits-consultation-group-bccg'
working_group_short: '/government/groups/aviation-statistics-team'
working_group_with_policies: '/government/groups/better-regulation-executive'

# Most visited working_group pages (2 September 2016)
working_group_1: '/government/groups/claims-management-regulator'
working_group_2: '/government/groups/disposal-services-authority'
working_group_3: '/government/groups/public-services-network'
working_group_4: '/government/groups/defence-medical-services'
working_group_5: '/government/groups/scientific-advisory-committee-on-nutrition'
working_group_6: '/government/groups/defence-relationship-management'
working_group_7: '/government/groups/veterans-welfare-service'
working_group_8: '/government/groups/uk-national-screening-committee-uk-nsc'
working_group_9: '/government/groups/uk-council-for-child-internet-safety-ukccis'

worldwide_office: '/world/organisations/british-consulate-general-barcelona/office/british-consulate-general-barcelona'
worldwide_office_without_access_details: '/world/organisations/british-consulate-general-alexandria/office/consulate-general-alexandria'
worldwide_office_with_many_locations: '/world/organisations/british-embassy-paris/office/british-embassy'
worldwide_office_with_non_default_logo: '/world/organisations/department-for-business-and-trade-ecuador/office/uk-trade-investment-ecuador'

worldwide_organisation: '/world/organisations/british-embassy-madrid'
worldwide_organisation_translation: '/world/organisations/british-embassy-madrid.es'
worldwide_organisation_with_secondary_corporate_info_pages: '/world/organisations/british-deputy-high-commission-hyderabad'
worldwide_organisation_without_corporate_info_pages: '/world/organisations/department-for-business-and-trade-germany'

worldwide_corporate_information_page: '/world/organisations/british-consulate-general-atlanta/about/recruitment'
worldwide_corporate_information_page_translation: '/world/organisations/british-consulate-general-shanghai/about/recruitment.zh'
worldwide_corporate_information_page_with_attachments: '/world/organisations/british-embassy-dakar/about/recruitment'
